language: node_js
node_js:
- '6'
- '5'
- '4'
- '0.12'
- '0.10'
after_success: npm run coveralls
deploy:
  provider: npm
  email: bargenson@gmail.com
  api_key:
    secure: "0PwmF3tBAnHuc6tHMqrmkOjqn6ZqlAzShfr0u60ERkilpgE6BHZdWqnHoUKXvHXKRbW2aNTUCwLZYIeDT6i6AXvVBcnlTaPcd7ppBsR9msdgpvM8jRMBLwmfgvAXMTlRhZVQANyCQIYWvAJAXLXdxiR54izlzzssD5S0BD9eHeRApL6/wtKCQY3KWH+JeC/x2C1ZNtm6E42+OjPnOZvGjtFDvcYiOJx55rTwbbUVPx0OW6X+WtA1ibFOumgrmIAK6z+3x1n/LBX7EUxVzmsFSIYJjlL56FCABYd1jSxU/yNWDiTgKlSJoXZZRk5Tzw+uuZDpAYpVbv96+fEnKJQ1vmW94RdyNIRUCu+loMGon2T+wiaiwvLxVfLNg5AI7vHEEaixkx9LjY64RDtiX1p3fuwk/LQUJ2DAD42Vi11eFhM4ndpgK331IGDzFQZLhCEgXnfWXhvfBbrXRpU0eJG0V0ft/2OfbbdR5gC0IfEvcCowDKBoYWIOAZYregfWA/Hgf/nzC72gZRSypg2TSDZD+9mukIwh9zF9sZQUOPTJnGrOHCN1Ne1oUClJpLy5+S4tOI4nxgQqEAIADBNc4NakhofTa8fzLLxI6YjCCuljhotUE9d8bp+LRnF66PRrjGG7sNFzoTBKIQXn7xfaATo0FPTWCq/gvZSF+hAbuzIaaKY="
  on:
    tags: true
    repo: barracksiot/messenger-javascript-client
